### PR TITLE
Feature/210 jwt in cookies

### PR DESCRIPTION
**Pull request by yossi-shasho**

### CODE REVIEW

**Comment by andyslack** [comment]
Hi @yossi-shasho this looks like it could have a large impact on the implementation on the client apps? Can you confirm?

**Comment by yossi-shasho** [comment]
they’ll only need to update @frontend-core , nothing more. No new env vars
etc.

**Comment by andyslack** [comment]
Fantastic, what about the backend? Looks like they might need to update the Auth decorator at least?

**Comment by yossi-shasho** [comment]
The backend won’t need any changes either, apart from updating core. The
decorator change isn’t even required I think. With postman I’m not sure a
change is even required: postman can keep cookies so just sending a post
request to the login route should let postman create the access token
cookie which it’ll send it the subsequent requests.
And yes, we can also bring back server support for the old bearer method
along side the cookie if we need it.

**Comment by yossi-shasho** [comment]
The main reason that I can think of to drop LS is protection against JS
injection or a malicious browser extension. Secure httpOnly Cookie is the
safest option because nothing in the webpage can access or control it.

**Comment by andyslack** [comment]
Can we create a new Auth decorator to support both bearer tokens and cookie, that way we can use the cookies on the frontend but still support bearer for API requests from backends/postman etc

**Comment by yossi-shasho** [comment]
Sure. Bringing back server support for the bearer token shouldn’t be a
problem. I’ll get to it.

**Comment by yossi-shasho** [comment]
I agree that it might not have been the most necessary feature to develop
as the security gain, while does exist, isn’t huge. However, at the moment
as it’s already been developed, it might not be a bad idea to start using
it: First, Integrating with it is as more simple process than with the old
bearer token, which will make future integrations quicker. Second, there is
nothing to change or update in the client apps to make it work except for
updating the core packages. And lastly, it does have a security advantage,
which might have made it a slightly better option to develop in the first
place. Therefore, I don’t see a reason why we shouldn’t use it.

**Comment by andyslack** [comment]
Agreed, once we add the ability to support both cookie and bearer I will release, not before as it will break live projects.

Once we support both, we can merge and release and then move the client frontends over to support cookie at the same time we can switch backend controllers to support both :)

**Comment by yossi-shasho** [comment]
@andyslack Bearer token support is restored + tests

**Comment by andyslack** [comment]
@yossi-shasho 

Can you confirm how we "migrate" client applications? Both backend and frontend please?

- In backend, what changes to controllers should we make?
- What frontend (if any, changes need to happen)?

**Comment by yossi-shasho** [comment]
@andyslack there's nothing to migrate or do

**Pull request merged**
