### PR TITLE
Allow search and query realtion fields

### PR DESCRIPTION
**Pull request by nathangemis**

### CODE REVIEW

**Comment by andyslack** [comment]
@nathangemis can you please add some [test cases here](https://github.com/juicyllama/framework/blob/main/backend/core/src/utils/typeorm/Query.test.spec.ts) for the new use case

Please make sure all tests are passing with the new feature.

Thanks in advanced

**Comment by nathangemis** [comment]
Perfect will do that now to complete the pull request 👌🏾

**Comment by andyslack** [comment]
@nathangemis can you resolve this conflict please

**Comment by nathangemis** [comment]
Hey @andyslack , need to change a think in buildWhere, test was not passing because of something that I did wrong.

**Pull request merged**
